version: 2
jobs:
  # build cmd/releasekit
  build:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/tombell/releasekit
    steps:
      - checkout
      - run: make dev

  # build cmd/coin with VERSION set to git tag
  build-release:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/tombell/releasekit
    steps:
      - checkout
      - run: |
          VERSION="${CIRCLE_TAG}" make dist dev
      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - dist/

  # run releasekit to generate release notes and attach build artifacts
  release:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/tombell/releasekit
    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-{{ .Revision }}
      - run: |
          dist/releasekit -t ${GITHUB_TOKEN} \
                          -o tombell \
                          -r releasekit \
                          -p $(git tag | sort -V | tail -2 | head -1) \
                          -n ${CIRCLE_TAG} \
                          --attachment dist/releasekit-linux-amd64 \
                          --attachment dist/releasekit-darwin-amd64 \
                          --attachment dist/releasekit-windows-amd64

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release:
          requires:
            - build-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
